spring:
  application:
    name: presize
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
  datasource:
    url: jdbc:h2:mem:test #localhost:port/h2-console? ?? ?? ? jdbc url ???
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console #localhost:port/h2-console? ?? ??
  codec:
    max-in-memory-size: 20MB
cloud:
  aws:
    stack: false
    s3:
      bucket: ${S3_BUCKET_NAME}
    region: ${S3_REGION}
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
ai:
  model:
    url:
      upscale: ${AI_MODEL_URL_UPSCALE}
      uncrop: ${AI_MODEL_URL_UNCROP}
      square: ${AI_MODEL_URL_SQUARE}
      health-check: ${AI_MODEL_URL_HEALTH_CHECK}
logging:
  file:
    name: logs/app.log
  level:
    root: info
