spring:
  config:
    activate:
      on-profile: test
  application:
    name: presize
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
  datasource:
    url: jdbc:h2:mem:test #localhost:port/h2-console? ?? ?? ? jdbc url ???
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console #localhost:port/h2-console? ?? ??
  codec:
    max-in-memory-size: 20MB
  cloud:
    aws:
      s3:
        enabled: false
cloud:
  aws:
    stack: false
    s3:
      bucket: dummy
    region: dummy
    credentials:
      accessKey: dummy
      secretKey: dummy
file:
  dir: /tmp
ai:
  model:
    url:
      upscale: dummy
      uncrop: dummy
      square: dummy
      health-check: dummy
