spring:
  application:
    name: presize
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
  datasource:
    url: jdbc:h2:mem:test #localhost:port/h2-console? ?? ?? ? jdbc url ???
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console #localhost:port/h2-console? ?? ??
  codec:
    max-in-memory-size: 20MB
file:
  dir: /tmp
ai:
  model:
    url: ${AI_MODEL_URL}
logging:
  file:
    name: logs/app.log
  level:
    root: debug
